name: CI/CD Workflow

on:
  push:
    branches:
      - t3c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

      # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t sakshambitsp/connect .

      # Push Docker image
    - name: Push Docker image
      run: |
        docker push sakshambitsp/connect:latest

      # SSH into EC2 and deploy
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull image from docker hub
      run:  sudo docker pull sakshambitsp/connect:latest
    - name: Run docker container
      run:  sudo docker run -d -p 3000:3000 \
               --restart unless-stopped \
               -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
               -e DIRECT_URL=${{ secrets.DIRECT_URL }} \
               -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
               -e NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
               -e NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
                sakshambitsp/connect

    